### ISSUE TITLE
Need some informations before flashing

### ISSUE THREAD

**Issue by wastez** [skgsergio/silabs-multiprotocol-firmware-zbgw04-usb#3]
Do you know if someone already flashed this firmware on a sonoff dongle-e?

Is zigbee2mqtt working with this firmware. 
i know it should but already read something like that there could be problems. 

Thanks for your help and your great work. 
Sorry for opening a issue for it.

**Comment by skgsergio** [comment]
I can't tell you if it is going to work for sonoff dongle-e as I don't own one, sorry.

I'm building the firmware [like this other repo](https://github.com/xsp1989/zigbeeFirmware/blob/master/firmware/Zigbee3.0_Dongle-NoSigned/EZSP/README.md) does and looks like is compatible with "ITead Zigbee 3.0 USB Dongle Model 9888010100045", which looks like it might the one you have: https://itead.cc/product/zigbee-3-0-usb-dongle/
