### ISSUE TITLE
Do you plan to update SDK 4.3 builds?

### ISSUE THREAD

**Issue by noogugae** [skgsergio/silabs-multiprotocol-firmware-zbgw04-usb#5]
Hi. I use your firmware very well.
But Home assistant Silicon Labs Multiprotocol needs SDK 4.3 now, and darkxst's firmware doesn't work for my ZB-GW04 v1.1 dongle.
Thanks

**Comment by skgsergio** [comment]
Please use this other firmware builds instead. It is using an automated builder which is more reliable than my manual builds (it is explained in my README): https://github.com/darkxst/silabs-firmware-builder

I use it myself.

**Comment by noogugae** [comment]
Hi. I tried darkxst's v4.3.0 firmware but it doesn't work.
It show the error below
''FATAL in function 'protocol_version_check' in file /usr/src/cpc-daemon/server_core/server_core.c at line #666 : Secondary Protocol v4 doesn't match CPCd Protocol v3'
Anyway. thanks for your help.

**Comment by skgsergio** [comment]
@noogugae Did you upgrade the silabs-multiprotocol addon in Home Assistant to version `2.2.0`? Looks like your device is correctly updated (Secondary Protocol Protocol v4) but the CPCd is requesting v3.

Restart the addon and check it is running the correct version by checking the log:

```
[15:59:24:868243] Info : [CPCd v4.3.0.0] [Library API v3] [RCP Protocol v4]
[...]
[15:59:24:953622] Info : Connected to Secondary
[15:59:24:955469] Info : Secondary Protocol v4
[15:59:24:960404] Info : Secondary CPC v4.3.0
```

**Comment by noogugae** [comment]
> 
OMG.
I  restored my Silicon Labs Multiprotocol add on to previous version.
After updating Silicon Labs Multiprotocol add on to v2.2.0, It works well.
Thanks
